# Generated by Django 4.1.7 on 2023-02-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
