# Generated by Django 4.1.7 on 2023-02-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='smugmug_key',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='smugmug_key',
        ),
        migrations.AddField(
            model_name='album',
            name='smugmug_uri',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='smugmug_uri',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
