# Generated by Django 4.1.7 on 2023-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_tag_delete_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.tag'),
        ),
    ]
