# Generated by Django 4.1.7 on 2023-03-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_tag_photos_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='medium_link',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
