# Generated by Django 4.1.7 on 2023-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_team_admins_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='largest_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
